/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PostManager } from "./PostManager";
export * as factories from "./factories";
export { PostManager__factory } from "./factories/PostManager__factory";
