name: CI Localhost Job

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  localhost-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Start Hardhat node
      run: |
        npx hardhat node --port 8545 &
        sleep 5

    - name: Run PostManager tests
      run: npx hardhat test --grep "PostManager"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: contract-artifacts
        path: |
          artifacts/
          typechain-types/
        retention-days: 7
