name: Deploy to Sepolia

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run mode (gas estimation only)'
        required: false
        default: false
        type: boolean

jobs:
  deploy-sepolia:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci


    - name: Deploy to Sepolia
      if: ${{ inputs.dry_run != true }}
      run: npx hardhat run scripts/deploy.ts --network sepolia
      env:
        SEPOLIA_URL: ${{ secrets.SEPOLIA_RPC_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_KEY }}

    - name: Upload deployment artifacts
      if: ${{ inputs.dry_run != true }}
      uses: actions/upload-artifact@v3
      with:
        name: deployment-artifacts
        path: |
          artifacts/
          typechain-types/
        retention-days: 30
