name: Deploy to Sepolia

on:
  workflow_dispatch:

jobs:
  deploy-sepolia:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SEPOLIA_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Compile contracts
      run: npx hardhat compile

    - name: Deploy to Sepolia
      run: npx hardhat run scripts/deploy.ts --network sepolia

    - name: Wait for contract indexing
      run: |
        echo "Waiting for contract to be indexed by Etherscan..."
        sleep 90

    - name: Verify contract on Etherscan
      run: |
        if [ -f "deployment-address.txt" ]; then
          CONTRACT_ADDRESS=$(cat deployment-address.txt)
          echo "Verifying contract at address: $CONTRACT_ADDRESS"
          npx hardhat verify --network sepolia "$CONTRACT_ADDRESS"
          echo "Contract verification completed"
        else
          echo "Deployment address file not found"
          exit 1
        fi
      continue-on-error: true

    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-artifacts
        path: |
          artifacts/
          typechain-types/
          deployment-address.txt
        retention-days: 30
